# Generated by Django 6.0.2 on 2026-02-21 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowrecord',
            name='user',
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='borrower_name',
            field=models.CharField(default='Guest', max_length=100),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='return_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='borrowed_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
