# Generated by Django 6.0.2 on 2026-02-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0002_remove_borrowrecord_user_borrowrecord_borrower_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='borrowed_date',
            field=models.DateField(default=None),
        ),
    ]
