# Generated by Django 6.0.2 on 2026-02-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0004_alter_borrowrecord_borrowed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='borrowed_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='return_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
